In [ ]:
import numpy as np  #import numpy 

In [ ]:
a = list(map(int, input().split())) # take nine integer input from the user

1 2 3 4 5 6 7 8 9


In [ ]:
mtrx = np.array(a).reshape(3, 3)
print(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
def calculate(a):
    eval = dict()
    mtrx = np.array(a).reshape(3, 3)
    eval["mean"] = [mtrx.mean(0).tolist(), mtrx.mean(1).tolist(), mtrx.mean()]
    eval["variance"] = [mtrx.var(0).tolist(), mtrx.var(1).tolist(), mtrx.var()]
    eval["standared deviation"] = [mtrx.std(0).tolist(), mtrx.std(1).tolist(), mtrx.std()]
    eval["sum"] = [mtrx.sum(0).tolist(), mtrx.sum(1).tolist(), mtrx.sum()]
    eval["max"] = [mtrx.max(0).tolist(), mtrx.max(1).tolist(), mtrx.max()]
    eval["min"] = [mtrx.min(0).tolist(), mtrx.min(1).tolist(), mtrx.min()]
    
    return eval

calculate(a)
  

{'max': [[7, 8, 9], [3, 6, 9], 9],
 'mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 5.0],
 'min': [[1, 2, 3], [1, 4, 7], 1],
 'standared deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'sum': [[12, 15, 18], [6, 15, 24], 45],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667]}